version: '3.7'
services:
  proxy:
    container_name: spfo_proxy
    image: nginx:alpine
    ports:
      - $PROXY_PORT:80
      - $PROXY_HTTPS_PORT:443
    environment:
      - IAM_SERVICE_ENDPOINT=$IAM_SERVICE_ENDPOINT
      - DOCKER_LOOPBACK_ADDRESS_HOST=$DOCKER_LOOPBACK_ADDRESS_HOST
      - BE_NPEFILING_PORT=$BE_NPEFILING_PORT
      - PROXY_PORT=$PROXY_PORT
      - PROXY_HTTPS_PORT=$PROXY_HTTPS_PORT
    volumes:
      - ./proxy:/etc/nginx
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  db:
    container_name: spfo_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD_ROOT
    ports:
      - $DB_PORT:3306
    volumes:
      - ./sp-db/mysql_init/my.cnf:/etc/mysql/my.cnf
      - ./sp-db/sql_scripts/:/docker-entrypoint-initdb.d/
  mongodb:
    container_name: eolf_integration_service_db
    environment:
      - MONGO_INITDB_DATABASE=eolf_integration
      - MONGO_INITDB_ROOT_USERNAME=eolf
      - MONGO_INITDB_ROOT_PASSWORD=eolf
    image: mongo:4.2.10
    volumes:
      - ./integration-db/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
  web:
    container_name: spfo_frontend
    image: spfo_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
      args:
        http_proxy: $HTTP_PROXY
    # required to prevent stopping container on "yarn start"
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ../frontend:/app
      - /app/node_modules
  submission-service:
    container_name: spfo_submission
    image: spfo_submission
    build:
      context: ../submission-service
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTP_PROXY
    ports:
      - $BE_NPEFILING_PORT:$BE_NPEFILING_PORT
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=$DB_DATABASE
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - BE_NPEFILING_STORAGE_PATH=$BE_NPEFILING_STORAGE_PATH
  file-service:
    container_name: spfo_file
    image: spfo_file
    build:
      context: ../file-service
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTP_PROXY
    ports:
      - 3002:3002
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=$FILE_DB_DATABASE
      - DB_USER=$FILE_DB_USER
      - DB_PASSWORD=$FILE_DB_PASSWORD
      - BE_NPEFILING_STORAGE_PATH=$BE_NPEFILING_STORAGE_PATH
  iam-service:
    container_name: iam_service
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=db
      - DB_PORT=3306
      - DB_SCHEMA=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
    - 7000:8000
    - 7443:8443
  eolf-integration:
    container_name: eolf_integration_service
    build:
      context: ../eolf-integration-service
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTP_PROXY
    environment:
      - DB_URI=mongodb://integration:integration@mongodb:27017/eolf_integration
      - SPRING_PROFILES_ACTIVE=oid
    ports:
      - '5001:5001'
    depends_on:
      - mongodb
    restart: always
